# Site
name: "Armored Code"
description: "A blog talking about offensive and defensive security and how to craft software in a secure way"

meta_description: "A blog talking about offensive and defensive security and how to craft software in a secure way"
logo: 'assets/images/armoredcode_heart.png'
favicon: 'assets/images/armoredcode_heart.png'
baseurl: ""
google_analytics: 'UA-17182118-1'
disqus: 'armoredblog'
mailchimp-list: 'https://armoredcode.us1.list-manage.com/subscribe/post?u=f136287d72c1e72ed99ee0542&amp;id=146dee4f3c'

# Authors
authors:
  thesp0nge:
    name: Paolo
    display_name: thesp0nge
    gravatar: 23e75747105bedfc499e962e399ad1ca
    email: paolo@codiceinsicuro.it
    web: https://codiceinsicuro.it
    twitter: https://twitter.com/thesp0nge
    description: "OSCP guy. I break code and rebuild it with security in mind, taekwon-do, husband, dad. Chaotic good drow ranger. I blog @codiceinsicuro and @the_armoredcode."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge

# PATH
source              : .
destination         : ./_site
permalink           : /blog/:title/
